### ISSUE TITLE
Any account gives access to any other account in NeoLine wallet without having to enter its password

### ISSUE THREAD

**Issue by gsmachado** [NeoNEXT/neoline#114]
Hey guys 👋 

This issue is a security threat in my humble opinion and should have the highest priority.

I have 4 different accounts in NeoLine. All 4 accounts have different passwords. **However, if I open ANY OF THESE 4 ACCOUNTS, I will have access to all other 3 without having to enter their password.**

Steps to reproduce:
- Create 2 different accounts on NeoLine (`Account 1` and `Account 2`)
- Close your browser
- Open your browser
- Click on NeoLine and open `Account 1` by typing its password
- Click on the avatar icon (top right within NeoLine) and change it to `Account 2`
- You will have access to `Account 2` without having to type its password (and you'll be able to create/sign any txs using `Account 2`)

My suggestion:
Ask for the password if you change accounts and the account is not unlocked yet for that "session".

**Comment by hacfox** [comment]
This is an open opinion, We collected a lot of feedbacks from users and changed it to the current mode. For one password like metamask,Can I question why I can access all wallets by entering a correct password? If I forget the password, privatekey, All wallets will be lost. The NeoLine can recover all the wallets by using another wallet's password.This way has helped users recover tens of millions of assets.However, there is no problem with what you said. If follow your mode, users will just reduce one way to recover assets and it is relatively safe because of isolation.

**Comment by gsmachado** [comment]
@hacfox I think that NeoLine should provide other ways to recover wallets.

The current behavior, in my opinion, mixes different concepts. Currently, each account has a password -- that's fine. Users automatically think that their account is protected ONLY with that password. However, allowing accounts to unlock any other account breaks this concept.

If you would like to have the property that multiple passwords unlock any account in NeoLine, then I would explicitly ask/instruct the user to create multiple passwords. Which, by the way, doesn't make sense to me.

What I think would be good, is: providing other ways for users to recover their accounts. For example, providing 12-word mnemonics, making them to download an encrypted wallet, or, even, making sure that they wrote down the WIF.

**Comment by hacfox** [comment]
@gsmachado Yeah.I agree with you. We have considered forcing users have to write down the private key. We will pay attention to this issue and adjust the logic of passwords to make it more reasonable.

**Comment by hacfox** [comment]
@gsmachado We have improved it on v3.5.0. If any issues, creat a new one.
