### ISSUE TITLE
Can you add custom network?

### ISSUE THREAD

**Issue by ediopia** [NeoNEXT/neoline#41]
Hi. I have been writing N3 smart contracts. I haven't found NEO wallets that can interact with N3 privatenet env. Can you add that support?

**Comment by hacfox** [comment]
Thanks for your attention, But there is no plan for this part so far, maybe it will be added in the future.

**Comment by djnicholson** [comment]
I also would find this feature really useful.

I would like to create an example of an N3 dapp that can b e used from within a browser.  I'd like to use [Neo Express](https://github.com/neo-project/neo-express) while developing my contract instead of N3 TestNet so I don't have to acquire TestNet GAS and wait for TestNet transactions.

**Comment by gsmachado** [comment]
Yes, for us this would be much appreciated as well! 👍

**Comment by hacfox** [comment]
@gsmachado @djnicholson @ediopia Hi, everyone, we have done a preliminary version of `private_chain`, just check [here](https://github.com/NeoNEXT/neoline/tree/private_chain).
